name: Process changesets

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js v22.10.0 (LTS)
        uses: ./.github/actions/setup-node-environment
        with:
          node-version: 22.10.0

      - name: Tag or publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          # pnpm release - in real repo
          publish: echo "released!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
