name: Ensure package structure and dependencies are correct

on:
  pull_request:
    types: [opened, reopened, edited]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js v22.10.0 (LTS)
        uses: ./.github/actions/setup-node-environment
        with:
          node-version: 22.10.0

      - name: Check for package version drift
        run: pnpm check-sync
